version: "0.2"
language: en
dictionaries:
    - css
    - html
    - typescript
enableFiletypes:
    - ignore
    - properties
    - astro
    - xml
files:
    - "**/.*"
    - "**/*.{astro,css,js,json,jsonc,html,md,scss,svelte,svg,yaml,yml,xml}"
useGitignore: true
ignorePaths:
    - pnpm-lock.yaml
    - data/**/*.json
    - dist/**
words:
    - astrolib
    - logoclouds
    - majestico
    - Satoshi
    - squircle
overrides:
    - language: en-gb
      filename: "**/*.md"
